fix processing of shipping method
netresearch/dhl-module-shipping-m2 pull request #26
Opened 2018-06-12 10:27 UTC by tuunit

Several Magento extensions use suffixes for the shipment method labels to
differentiate between the different DHL package types. For this reason no
'Create Label' checkbox is displayed in the backend for these extensions.
Because the onProcessMethods function only returns true if the label exactly
matches the extensions carrier name.

One example extension would be the 'MatrixRate Table Rate Shipping' by
WebShopApps. Which generate label names like 'matrixrate_500' for 'DHL Paket'
and 'matrixrate_509' for 'DHL Paket International', but does have the carrier
name 'matrixrate'.

2018-06-12 10:53 UTC, powli requested changes

2018-06-12 10:53 UTC, powli commented on Model/Config/ModuleConfig.php
> +            if (strpos($shippingMethod, $method)) {
`strpos($shippingMethod, $method)` can return 0 as a valid result, which will result in a false negative. It's better to do a type save check here `strpos($shippingMethod, $method) !== false`.

2018-06-12 12:12 UTC, powli approved these changes

2018-06-12 15:29 UTC, powli commented
@tuunit: Change has been merged in our internal repo and will be released in this repository with the next public release.

2018-06-12 15:29 UTC, closed without merging

2018-06-22 05:51 UTC, MarcusWolschon commented
Why do you close issues in this repository when they have not yet been fixed in THIS repository?
How are people downloading what they currently find here know about contained, known bugs ?
When is "next public release"?

2018-06-22 09:50 UTC, ngolatka commented
Change will be included in upcoming version 0.9.0 (no exact release date known yet, sorry).

2018-06-22 09:58 UTC, simonmaass commented
maybe like a estimated date? weeks? months?

2018-06-22 10:56 UTC, ngolatka commented
Probably weeks rather than months. But in the end, it isn't our decision, but DHL's.

2018-07-24 13:13 UTC, powli commented
@simonmaass, @MarcusWolschon, @tuunit:

Fix released with [0.9.0](https://github.com/netresearch/dhl-module-shipping-m2/releases/tag/0.9.0).

2018-07-24 13:49 UTC, simonmaass commented
@powli great to hear - thank you!